### ISSUE TITLE
Tray icon disappears in the last version  of criptext  0.30.1-1  - Linux

### ISSUE THREAD

**Issue by ciciolina** [Criptext/Criptext-Email-React-Client#1509]
**Describe the bug**
The tray icon dissapear in the last version of criptext 0.30.1.1, the tray icon never appears in the tray-bar, after review the cli output im sure its a problem related to the upgrade version not kernel or electron related, after back to the version 0.29.4-1 all  works perfect.

**To Reproduce**
1. Go to 'criptext app'
2. Open 'the app'
3. Close  'the app'
4. The tray icon never appears and the app process runs behind until you "kill" it or close the app from  file -> quit 

**Expected behavior**
On other versions if you close the app (from X icon), the app process run and you can see a tray icon informing the app its running, you can close or open (and execute other options) the app from tray icon. (its a visual alert near to the system tray icons).  

**Screenshots (Optional)**

**Device and System information (please complete the following information):**
 - Device: [Thinkpad T4XX]
 - OS Version: [Arch Linux x86_64 // 5.8.4-arch1-1 // Electron v9.2.1]
 - App Version: [criptext  0.30.1-1]

**Additional information**
i run the app from terminal this is the output from  criptext  0.30.1-1 version:

(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(electron) 'setResizable function' is deprecated and will be removed. Please use 'resizable property' instead.
{"message":"statusCode: 200","level":"info","timestamp":"2020-08-18T12:17:21.749Z"}
{"message":"Database Current Version : {"id":1,"value":4}","level":"info","timestamp":"2020-08-18T12:17:22.222Z"}
(electron) 'getBadgeCount function' is deprecated and will be removed. Please use 'badgeCount property' instead.
(node:13816) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:13816) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
Checking for update
{"message":"Backups : []","level":"debug","timestamp":"2020-08-18T12:17:24.044Z"}
Update for version 0.30.1 is not available (latest version: 0.30.1, downgrade is disallowed).

i run again after downgrade to  0.29.4 version:
{"message":"statusCode: 200","level":"info","timestamp":"2020-08-18T12:26:42.768Z"}
{"message":"Backups : []","level":"debug","timestamp":"2020-08-18T12:26:45.270Z"}
Checking for update
Found version 0.30.1 (url: Criptext-0.30.1.AppImage)
Downloading update from Criptext-0.30.1.AppImage
updater cache dir: /home/c/.cache/criptext-updater
No cached update info available
Error: Error: APPIMAGE env is not defined
at newError (/opt/criptext-bin/resources/app.asar/node_modules/builder-util-runtime/out/index.js:212:17)
at Object.task (/opt/criptext-bin/resources/app.asar/node_modules/electron-updater/out/AppImageUpdater.js:106:52)
at AppImageUpdater.executeDownload (/opt/criptext-bin/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:741:25) 

the 0.29.4 version works perfectly, the  0.30.1-1 version dont (tray icon vanished).

Thanks and i hope you can look this issue before the next release.

**Comment by ciciolina** [comment]
CMON!!! more than a month and no answer? i found the code its at least bad written, many errors and a lot of "bloatware code" lines and files... i dont know how but its unbelievable that like a user (PAID USER), i need to look into the code and try to figure out why dont work... why you change the good code of old versions and fuc# it out the new releases, im a little pissed about i found... first, why you  dont write a specific LINUX lines on tray.js file? why i found a ton of errors on manifest.json please run the criptext app on a VM with Arch Linux XFCE and update, after that run it again via terminal and you will see, PLEASE UPGRADE THE CODE TO ELECTRON 9.2
look an example:
[https://i.imgur.com/jUB6bnZ.png](url)

And i found this too on /destfolder/userData/ .... yes its 2 user folders full of mails, at least are encripted but why do you have this on your installer? 

[https://i.imgur.com/a5rQBwL.png](url)

Please fix your code or made an auditory if you dont like see your users complains!!!
